# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 300)
        self.table2 = QtWidgets.QTableWidget(Form)
        self.table2.setGeometry(QtCore.QRect(20, 40, 721, 191))
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(0)
        self.table2.setRowCount(0)
        self.push_restart = QtWidgets.QPushButton(Form)
        self.push_restart.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.push_restart.setObjectName("push_restart")
        self.push_update = QtWidgets.QPushButton(Form)
        self.push_update.setGeometry(QtCore.QRect(660, 10, 75, 23))
        self.push_update.setObjectName("push_update")
        self.push_add = QtWidgets.QPushButton(Form)
        self.push_add.setGeometry(QtCore.QRect(20, 250, 75, 23))
        self.push_add.setObjectName("push_add")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(280, 260, 471, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 240, 571, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 260, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(260, 10, 16, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(290, 10, 51, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактирование"))
        self.push_restart.setText(_translate("Form", "Обновить"))
        self.push_update.setText(_translate("Form", "Изменить"))
        self.push_add.setText(_translate("Form", "Добавить"))
        self.label.setText(_translate("Form", "Введите сорт, степень обжарки, молотый или в зернах, описание вкуса, цена и объем упаковки"))
        self.label_2.setText(_translate("Form", "Ввод через запятую: -->"))
        self.label_3.setText(_translate("Form", "ID"))
